name: animated_glitch
description:  Animated Glitch is a Flutter package that allows you to easily create glitch effects and control them
version: 1.0.1
homepage: https://github.com/feduke-nukem/animated_glitch
repository: https://github.com/feduke-nukem/animated_glitch
issue_tracker: https://github.com/feduke-nukem/animated_glitch/issues

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.3 
